### ISSUE TITLE
Butterknife Unbind

### ISSUE THREAD

**Issue by abiemann** [mkoslacz/Moviper#44]
After having read https://github.com/JakeWharton/butterknife/issues/585
and then looking at the module https://github.com/mkoslacz/Moviper/blob/master/moviper-butterknife/src/main/java/com/mateuszkoslacz/moviper/base/view/fragment/autoinject/butterknife/ViperButterKnifeFragment.java

I have to ask : is the unbinding missing from ViperButterKnifeFragment? It looks like it.

**Comment by mkoslacz** [comment]
It was. Shall be fixed in [v2.0.4](https://github.com/mkoslacz/Moviper/releases/tag/v2.0.4). 

Please reopen if it is insufficient.
